// @/app/@right/(_PRIVAT_ROUTES)/admin/(_routing)/pages/[slug]/(_service)/(_components)/admin-pages/step1.tsx
"use client";

import React from "react";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { useNavigationMenu } from "@/app/@right/(_service)/(_context)/nav-bar-provider";
import { useSession } from "next-auth/react";
import { UserType } from "@prisma/client";
import { PageData } from "@/app/@right/(_service)/(_types)/page-types";
import { PageNotFound } from "../../../page-not-found";
import { AdminPageInfoProps } from "../../../../(_types)/admin-page-sections-types";
import { findPageBySlug } from "../../../../(_utils)/page-helpers";
import { StepActivationCard } from "../../../step-activation-card";

// slug will === "step1"
export function AdminPageStep6({ slug }: AdminPageInfoProps) {
  const { categories, loading, initialized } = useNavigationMenu();
  const { data: session } = useSession();
  const role: UserType = session?.user?.type || "guest";

  // Show loading state with theme-aware colors
  if (loading || !initialized) {
    return (
      <div className="flex items-center justify-center py-12">
        <LoadingSpinner />
        <span className="ml-3 text-muted-foreground">Loading page data...</span>
      </div>
    );
  }

  // Adapt to existing findPageBySlug function
  const searchResult = findPageBySlug(categories, slug);

  // Show error state if page not found with theme-aware styling
  if (!searchResult) {
    return <PageNotFound slug={slug} />;
  }

  let page: PageData;
  let category: { title: string };

  if (
    typeof searchResult === "object" &&
    "page" in searchResult &&
    "category" in searchResult
  ) {
    page = searchResult.page as PageData;
    category = searchResult.category as { title: string };
  } else {
    page = searchResult as PageData;
    category = { title: "Unknown Category" };
  }

  return (
    <div className="space-y-6">
      <div className="max-w-4xl mx-auto p-6">
        <StepActivationCard stepKey="step6" />

        {/* Additional step content after activation */}
        <div className="mt-8 space-y-4">
          <h3 className="text-lg font-semibold">
            Content Architecture Builder: Perplexity Response Processing &
            Section Framework Creation
          </h3>
          <p className="text-muted-foreground">
            This critical processing step features a singular, focused
            functionality: importing and validating the structured response
            object generated by Perplexity Pro from your previous system
            instruction.
            <br />
            Upon successful upload, the system performs comprehensive validation
            and intelligently parses the response to create one or multiple
            content sections within your project architecture.
            <br />
            Each generated section remains intentionally empty of final content
            but contains rich, detailed system instructions derived from your
            consolidated knowledge base, competitor insights, and strategic
            parameters.
            <br />
            These embedded instructions serve as precise generation blueprints
            that will power individual section content creation in subsequent
            steps.
            <br />
            The processing automatically establishes database records in both
            pageData.SectionsInfo and sections models, utilizing cuid v2
            generators for unique, collision-resistant identifiers.
            <br />
            All section data is persistently stored in Vercel Blob with
            automatic versioning for every update, ensuring reliable data
            integrity and seamless scalability.
            <br />
            The successful completion of this mandatory step transforms your
            strategic planning into actionable content frameworks - empty
            sections that are fully prepared, structured, and equipped with the
            necessary intelligence for targeted AI content generation.
            <br />
            This foundation is essential before proceeding to the final content
            creation phase.
          </p>
        </div>
      </div>
    </div>
  );
}
